name: Deploy to GitHub Pages

on:
  push:
    branches: [main, docs]
    paths:
      [
        website/**,
        .github/workflows/**,
        cli/**,
        sdks/**,
        javascript/common/**,
        javascript/sbv2-scripts/**,
      ]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install global deps
        working-directory: .
        run: |
          npm i -g typescript ts-node @types/node

      - name: Install sbv2-scripts
        working-directory: javascript/sbv2-scripts
        run: |
          npm ci
          npm link

      - name: Install @switchboard-xyz/cli dependencies
        working-directory: cli
        run: |
          yarn install --frozen-lockfile --network-timeout=1000000
          yarn build

      - name: Generate CLI Docs
        working-directory: .
        run: |
          sbv2-scripts cli ./cli/README.md ./website/docs/dev/cli

      - name: Install @switchboard-xyz/common dependencies
        working-directory: javascript/common
        run: |
          npm ci

      - name: Install @switchboard-xyz/oracle dependencies
        working-directory: javascript/oracle
        run: |
          npm ci

      - name: Install @switchboard-xyz/aptos.js dependencies
        working-directory: sdks/aptos
        run: |
          yarn install --frozen-lockfile --network-timeout=1000000

      - name: Install @switchboard-xyz/near.js dependencies
        working-directory: sdks/near/javascript/near.js
        run: |
          yarn install --frozen-lockfile --network-timeout=1000000

      - name: Install @switchboard-xyz/switchboard-v2 dependencies
        working-directory: sdks/solana/javascript/switchboard-v2
        run: |
          npm ci

      - name: Install @switchboard-xyz/solana.js dependencies
        working-directory: sdks/solana/javascript/solana.js
        run: |
          npm ci

      # - name: Install @switchboard-xyz/sbv2-lite dependencies
      #   working-directory: sdks/solana/javascript/sbv2-lite
      #   run: |
      #     npm ci

      # - name: Install @switchboard-xyz/sbv2-utils dependencies
      #   working-directory: sdks/solana/javascript/sbv2-utils
      #   run: |
      #     npm ci

      - name: Install @switchboard-xyz/evm.js dependencies
        working-directory: sdks/evm/javascript/evm.js
        run: |
          npm ci

      - name: Install @switchboard-xyz/starknet.js dependencies
        working-directory: sdks/starknet/javascript/starknet.js
        run: |
          npm install

      - name: Install @switchboard-xyz/sui.js dependencies
        working-directory: sdks/sui/javascript/sui.js
        run: |
          npm install

      - name: Build website
        working-directory: website
        run: |
          yarn install --frozen-lockfile --network-timeout=1000000
          yarn build:all
      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./website/public
          # Assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
